unit_test_Part2:
	gcc -g3 -o UnitTestPart2 UnitTestPart2.c ./Unity-master/src/unity.c ../src/Queue.c ../src/DynamicTrie.c ../src/BloomFilter.c  ../src/LinearHash.c ../src/AssistingFunctions.c ../src/MurmurHash2.c ../src/StaticTrie.c ../src/StaticLinearHash.c

unit_test_Part1:
	gcc -g3 -o mainTEST_TRIE mainTEST_TRIE.c ./Unity-master/src/unity.c ./../src/Queue.c
	
clean_part1:
	rm mainTEST_TRIE

clean_part2:
	rm UnitTestPart2
